version: '2.1'
networks:
  monitoring:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  app:
      container_name: app
      build:
        context: demo
      ports:
        - 8081:8081
      mem_limit: 256m
      memswap_limit: 256m
      expose:
        - 8081
      networks:
        - monitoring