global:
  scrape_interval: 30s
  scrape_timeout: 30s
scrape_configs:
  - job_name: "app-demo"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
